import { EVModel, VehicleSegment } from '@shared/types';

// Static EV model library — mirrors the database seed.sql
// Used as fallback when the backend is not available
export const EV_MODELS_MOCK: EVModel[] = [
  // ── Small Vans ──────────────────────────────────────────────
  {
    id: 'mock-1',
    manufacturer: 'Renault',
    model: 'Kangoo E-Tech Electric',
    segment: VehicleSegment.SMALL_VAN,
    battery_gross_kwh: 45.0,
    battery_usable_kwh: 40.0,
    nominal_consumption_kwh_100km: 22.0,
    max_ac_kw: 11.0,
    max_dc_kw: null,
    payload_kg: 800,
    cargo_volume_m3: 3.9,
    purchase_price: 39900,
    lease_monthly: 589,
    notes: 'Kurze Lieferkonfiguration, ideal für Stadtlieferungen',
    is_active: true,
  },
  {
    id: 'mock-2',
    manufacturer: 'Stellantis',
    model: 'Citroën ë-Berlingo L1',
    segment: VehicleSegment.SMALL_VAN,
    battery_gross_kwh: 50.0,
    battery_usable_kwh: 45.0,
    nominal_consumption_kwh_100km: 23.0,
    max_ac_kw: 11.0,
    max_dc_kw: 100.0,
    payload_kg: 750,
    cargo_volume_m3: 3.9,
    purchase_price: 41500,
    lease_monthly: 620,
    notes: 'Kompakte Nutzfahrzeugversion, auch als Peugeot e-Partner verfügbar',
    is_active: true,
  },
  {
    id: 'mock-3',
    manufacturer: 'Stellantis',
    model: 'Peugeot e-Partner L2',
    segment: VehicleSegment.SMALL_VAN,
    battery_gross_kwh: 50.0,
    battery_usable_kwh: 45.0,
    nominal_consumption_kwh_100km: 23.5,
    max_ac_kw: 11.0,
    max_dc_kw: 100.0,
    payload_kg: 800,
    cargo_volume_m3: 4.4,
    purchase_price: 43200,
    lease_monthly: 640,
    notes: 'Verlängerte Version mit größerem Laderaum',
    is_active: true,
  },
  {
    id: 'mock-4',
    manufacturer: 'Volkswagen',
    model: 'Caddy Cargo e',
    segment: VehicleSegment.SMALL_VAN,
    battery_gross_kwh: 45.0,
    battery_usable_kwh: 38.0,
    nominal_consumption_kwh_100km: 22.0,
    max_ac_kw: 11.0,
    max_dc_kw: null,
    payload_kg: 710,
    cargo_volume_m3: 3.1,
    purchase_price: 38700,
    lease_monthly: 575,
    notes: 'Kompaktes Nutzfahrzeug für urbane Logistik',
    is_active: true,
  },
  {
    id: 'mock-5',
    manufacturer: 'Ford',
    model: 'E-Transit Custom',
    segment: VehicleSegment.SMALL_VAN,
    battery_gross_kwh: 64.0,
    battery_usable_kwh: 57.0,
    nominal_consumption_kwh_100km: 24.0,
    max_ac_kw: 11.4,
    max_dc_kw: 115.0,
    payload_kg: 1136,
    cargo_volume_m3: 5.6,
    purchase_price: 48900,
    lease_monthly: 720,
    notes: 'Neue Plattform, sehr hohe Nutzlast im Segment',
    is_active: true,
  },

  // ── Large Vans ──────────────────────────────────────────────
  {
    id: 'mock-6',
    manufacturer: 'Mercedes-Benz',
    model: 'eSprinter 312 L2H2',
    segment: VehicleSegment.LARGE_VAN,
    battery_gross_kwh: 113.0,
    battery_usable_kwh: 100.0,
    nominal_consumption_kwh_100km: 27.0,
    max_ac_kw: 22.0,
    max_dc_kw: 80.0,
    payload_kg: 904,
    cargo_volume_m3: 10.5,
    purchase_price: 69900,
    lease_monthly: 1100,
    notes: 'Standard-Hochraumkasten, Standardversion',
    is_active: true,
  },
  {
    id: 'mock-7',
    manufacturer: 'Mercedes-Benz',
    model: 'eSprinter 312 L3H2',
    segment: VehicleSegment.LARGE_VAN,
    battery_gross_kwh: 113.0,
    battery_usable_kwh: 100.0,
    nominal_consumption_kwh_100km: 28.0,
    max_ac_kw: 22.0,
    max_dc_kw: 80.0,
    payload_kg: 736,
    cargo_volume_m3: 11.5,
    purchase_price: 74500,
    lease_monthly: 1180,
    notes: 'Langversion, für größere Frachten',
    is_active: true,
  },
  {
    id: 'mock-8',
    manufacturer: 'Volkswagen',
    model: 'e-Crafter 35 L3H3',
    segment: VehicleSegment.LARGE_VAN,
    battery_gross_kwh: 35.8,
    battery_usable_kwh: 32.0,
    nominal_consumption_kwh_100km: 27.0,
    max_ac_kw: 7.2,
    max_dc_kw: null,
    payload_kg: 1000,
    cargo_volume_m3: 10.7,
    purchase_price: 67800,
    lease_monthly: 1050,
    notes: 'Bewährter Elektrivan, ältere Generation',
    is_active: true,
  },
  {
    id: 'mock-9',
    manufacturer: 'Ford',
    model: 'E-Transit 350 L3H3',
    segment: VehicleSegment.LARGE_VAN,
    battery_gross_kwh: 68.0,
    battery_usable_kwh: 61.5,
    nominal_consumption_kwh_100km: 28.0,
    max_ac_kw: 11.3,
    max_dc_kw: 115.0,
    payload_kg: 1616,
    cargo_volume_m3: 15.1,
    purchase_price: 62400,
    lease_monthly: 960,
    notes: 'Beste Nutzlast im Segment, schnelles DC-Laden',
    is_active: true,
  },
  {
    id: 'mock-10',
    manufacturer: 'Stellantis',
    model: 'Citroën ë-Jumper L3H2',
    segment: VehicleSegment.LARGE_VAN,
    battery_gross_kwh: 75.0,
    battery_usable_kwh: 70.0,
    nominal_consumption_kwh_100km: 28.0,
    max_ac_kw: 22.0,
    max_dc_kw: 50.0,
    payload_kg: 1100,
    cargo_volume_m3: 13.0,
    purchase_price: 65000,
    lease_monthly: 1020,
    notes: 'Neue Generation mit verbesserter Reichweite',
    is_active: true,
  },
  {
    id: 'mock-11',
    manufacturer: 'Stellantis',
    model: 'Peugeot e-Boxer L3H2',
    segment: VehicleSegment.LARGE_VAN,
    battery_gross_kwh: 75.0,
    battery_usable_kwh: 70.0,
    nominal_consumption_kwh_100km: 28.0,
    max_ac_kw: 22.0,
    max_dc_kw: 50.0,
    payload_kg: 1080,
    cargo_volume_m3: 13.0,
    purchase_price: 65500,
    lease_monthly: 1025,
    notes: 'Baugleich mit ë-Jumper, Peugeot-Variante',
    is_active: true,
  },
  {
    id: 'mock-12',
    manufacturer: 'Stellantis',
    model: 'Fiat E-Ducato L3H2',
    segment: VehicleSegment.LARGE_VAN,
    battery_gross_kwh: 79.0,
    battery_usable_kwh: 73.0,
    nominal_consumption_kwh_100km: 28.0,
    max_ac_kw: 22.0,
    max_dc_kw: 50.0,
    payload_kg: 1045,
    cargo_volume_m3: 13.1,
    purchase_price: 66000,
    lease_monthly: 1035,
    notes: 'Leicht größere Batterie als Peugeot/Citroën-Variante',
    is_active: true,
  },
  {
    id: 'mock-13',
    manufacturer: 'Renault',
    model: 'Master E-Tech Electric',
    segment: VehicleSegment.LARGE_VAN,
    battery_gross_kwh: 87.0,
    battery_usable_kwh: 82.0,
    nominal_consumption_kwh_100km: 27.0,
    max_ac_kw: 22.0,
    max_dc_kw: null,
    payload_kg: 1200,
    cargo_volume_m3: 13.0,
    purchase_price: 68000,
    lease_monthly: 1090,
    notes: 'Höchste Batteriekapazität im Segment, hohe Nutzlast',
    is_active: true,
  },
  {
    id: 'mock-14',
    manufacturer: 'MAN',
    model: 'eTGE 3.5t',
    segment: VehicleSegment.LARGE_VAN,
    battery_gross_kwh: 35.8,
    battery_usable_kwh: 32.0,
    nominal_consumption_kwh_100km: 26.0,
    max_ac_kw: 7.2,
    max_dc_kw: null,
    payload_kg: 993,
    cargo_volume_m3: 11.0,
    purchase_price: 66500,
    lease_monthly: 1045,
    notes: 'VW e-Crafter Pendant aus dem MAN-Konzern',
    is_active: true,
  },
  {
    id: 'mock-15',
    manufacturer: 'Stellantis',
    model: 'Opel Movano-e L3H2',
    segment: VehicleSegment.LARGE_VAN,
    battery_gross_kwh: 70.0,
    battery_usable_kwh: 64.0,
    nominal_consumption_kwh_100km: 28.0,
    max_ac_kw: 11.5,
    max_dc_kw: 50.0,
    payload_kg: 1080,
    cargo_volume_m3: 13.0,
    purchase_price: 64000,
    lease_monthly: 1000,
    notes: 'Kompetitives Angebot, Vauxhall-Pendants verfügbar',
    is_active: true,
  },

  // ── Medium Trucks ────────────────────────────────────────────
  {
    id: 'mock-16',
    manufacturer: 'Renault',
    model: 'D Z.E. 16t',
    segment: VehicleSegment.MEDIUM_TRUCK,
    battery_gross_kwh: 265.0,
    battery_usable_kwh: 245.0,
    nominal_consumption_kwh_100km: 55.0,
    max_ac_kw: 43.0,
    max_dc_kw: null,
    payload_kg: 6500,
    cargo_volume_m3: null,
    purchase_price: 185000,
    lease_monthly: 3200,
    notes: 'Stadtlieferfahrzeug 16t zGG, ideal für KEP',
    is_active: true,
  },
  {
    id: 'mock-17',
    manufacturer: 'Volvo',
    model: 'FL Electric 16t',
    segment: VehicleSegment.MEDIUM_TRUCK,
    battery_gross_kwh: 265.0,
    battery_usable_kwh: 250.0,
    nominal_consumption_kwh_100km: 52.0,
    max_ac_kw: 22.0,
    max_dc_kw: 150.0,
    payload_kg: 9200,
    cargo_volume_m3: null,
    purchase_price: 210000,
    lease_monthly: 3600,
    notes: 'Modulares Batteriesystem, hohe Nutzlast',
    is_active: true,
  },
];
